server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA-DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: ${RABBIT_MQ}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}


# cors
cors:
  allowed-origins: ${ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true


#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: diary-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration: ${REFRESH_TOKEN_EXP}

firebase:
  key:
    path: ${FIREBASE_KEY_PATH}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  terms:
    version: 1.0.0


ai:
  secret-key: ${AI_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

